# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_nform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nform',
        ),
    ]
